export const SOROBAN_NETWORK = 'TESTNET'; // Use 'PUBLIC' for mainnet
export const SOROBAN_RPC_URL = 'https://soroban-testnet.stellar.org';
export const SOROBAN_NETWORK_PASSPHRASE = 'Test SDF Network ; September 2015';

export const CONTRACTS = {
  SLICE_TOKEN: 'CACFX6EO72DX2HC5JC7M66TDESTEQ6VOYZXKVKB6NOH52LIL4GQDRDIL',
  OVEN_NFT: 'CBC3AGOZTWKEII45VBRWLOGMBNGBJ6ABPP6MOFAZM2HFHP2NKPXXEWXB'
};
